LANGUAGE_CODES = ["en", "zh", "fr", "ja",
                  "ru", "pt", "ca", "fa",
                  "ar", "fi", "hu", "id",
                  "es", "it", "war", "ceb",
                  "nl", "de", "sv", "ro",
                  "cs", "ko", "sr", "ms",
                  "tr", "min", "eo", "eu",
                  "kk", "da", "bg", "sk",
                  "hy", "he", "lt", "sl",
                  "et", "uz", "gl", "nn",
                  "la", "vo", "simple",
                  "el", "ce", "be", "ka",
                  "hi", "az", "th", "ur",
                  "oc", "mk", "ta", "mg",
                  "new", "tt", "cy", "tl",
                  "bs", "br", "ne", "gu",
                  "io", "bpy", "nds", "ku",
                  "als", "pa", "su", "kn",
                  "bar", "ckb", "ia", "arz"]
